batches_per_epoch: 10
cond_dim: 11
decoder_layers:
- 32
- 32
device: cpu
encoder_layers:
- 32
- 32
epochs: 100
gamma: 0.75
latent_dim: 6
lr: 0.0005
output_dim: 12
prior_layers:
- 32
- 32
save_epochs: 10
step_size: 50
val_epochs: 10
