function out1 = A(f1,f2,f3,f4,ox,oy,oz,phi,th,varphi)
%A
%    OUT1 = A(F1,F2,F3,F4,OX,OY,OZ,PHI,TH,VARPHI)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    28-Feb-2024 20:55:04

t2 = cos(phi);
t3 = cos(th);
t4 = cos(varphi);
t5 = sin(phi);
t6 = sin(th);
t7 = sin(varphi);
t12 = -f2;
t13 = -f4;
t16 = f1+f2+f3+f4;
t8 = oy.*t2;
t9 = oz.*t2;
t10 = oy.*t5;
t11 = oz.*t5;
t14 = 1.0./t3;
t20 = f1+f3+t12+t13;
t15 = t14.^2;
t17 = -t11;
t18 = t9+t10;
t19 = t8+t17;
out1 = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,(t3.*t4.*t5.*t16)./5.0+(t2.*t3.*t7.*t20)./5.0,t6.*t14.*t19,-t18,t14.*t19,0.0,0.0,0.0,0.0,(t2.*t4.*t6.*t16)./5.0-(t5.*t6.*t7.*t20)./5.0,t15.*t18,0.0,t6.*t15.*t18,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,oz.*(5.0./8.0),oy.*(-6.0./7.0),0.0,0.0,t5.*t6.*t14,t2,t5.*t14,oz./2.0,0.0,ox.*(-6.0./7.0),0.0,0.0,t2.*t6.*t14,-t5,t2.*t14,oy./2.0,ox.*(5.0./8.0),0.0],[8,8]);
