function out1 = B(phi,th,varphi)
%B
%    OUT1 = B(PHI,TH,VARPHI)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    28-Feb-2024 20:55:05

t2 = cos(th);
t3 = cos(varphi);
t4 = sin(varphi);
t5 = phi+varphi;
t7 = -varphi;
t6 = cos(t5);
t8 = t3.*2.0e+1;
t10 = phi+t7;
t12 = t3.*(2.65e+2./4.0);
t13 = t4.*(1.6e+2./7.0);
t9 = -t8;
t11 = cos(t10);
t14 = -t12;
t15 = -t13;
t16 = (t2.*t6)./5.0;
t20 = t12+1.55e+2./4.0;
t17 = -t16;
t18 = (t2.*t11)./5.0;
t21 = t14-1.55e+2./4.0;
t19 = -t18;
out1 = reshape([0.0,t17,0.0,0.0,0.0,t21,t9,t13,0.0,t19,0.0,0.0,0.0,t20,t9,t15,0.0,t17,0.0,0.0,0.0,t21,t8,t15,0.0,t19,0.0,0.0,0.0,t20,t8,t13],[8,4]);
